# Generated by Django 5.0.6 on 2024-05-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0027_remove_irasai_fk_forumasid_forumas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptai',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
