# Generated by Django 5.0.6 on 2024-05-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0028_receptai_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptai',
            name='aprasas',
            field=models.CharField(max_length=300),
        ),
    ]
