# Generated by Django 4.2.7 on 2024-06-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0029_alter_receptai_aprasas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valgymai',
            name='bendras_baltymas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='valgymai',
            name='bendras_fenilalaninas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
